### ISSUE TITLE
How do I install poses

### ISSUE THREAD

**Issue by wangxudong1998** [MariaPriisalu/spl#4]
When I run RLmain.py and evaluate.py, the system reports an error ModuleNotFoundError: No module named 'positions'.
And even though I install poses-0.0.1 by pip install poses, the error still exists.

Traceback (most recent call last):
  File "RL/RLmain.py", line 23, in <module>
    from environment_test import TestEnvironment
  File "/home/wangxd/spl/RL/environment_test.py", line 3, in <module>
    from environment import Environment
  File "/home/wangxd/spl/RL/environment.py", line 7, in <module>
    from environment_abstract import AbstractEnvironment
  File "/home/wangxd/spl/RL/environment_abstract.py", line 13, in <module>
    import colmap.reconstruct
  File "RL/../colmap/reconstruct.py", line 14, in <module>
    from poses.boundingboxes import find_people_bd
ModuleNotFoundError: No module named 'poses'

**Comment by MariaPriisalu** [comment]
Hi thank you for letting me know of this error. 

You can just comment out line 14 "from poses.boundingboxes import find_people_bd" in  "RL/../colmap/reconstruct.py".

I have tried to remove unused code in the repository but must have missed this. Previously poses was a folder of some experimental code that has been removed as it is unused.
